# Server Configuration
server.port=8080

# MongoDB Configuration
spring.data.mongodb.uri=${MONGO_URI}/DATABASE_NAME
spring.data.mongodb.auto-index-creation=true


# Logging
logging.level.org.springframework.data.mongodb.core=DEBUG
# CORS Configuration-


# DeepSeek API Config (Pratham AI)
deepseek.api.key=${DEEPSEEK_API_KEY}
deepseek.api.url=https://api.deepseek.com/v1/chat/completions
deepseek.model=deepseek-chat